services:
  backend:
    build:
      target: dev
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    environment:
      - NODE_ENV=development
    env_file:
      - .env
